platform :ios, "12.0"
use_frameworks!

plugin "cocoapods-binary-cache"

config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "local" => "prebuilt-frameworks"
    }
  },
  device_build_enabled: true,
  xcframework: true
)

target "Example" do
  pod "Charts", :binary => true
  pod "GoogleUtilities/Network", :binary => true
  pod "RxCocoa", :binary => true
end
